language: go
sudo: required
env:
    - GIMME_ARCH=amd64
go:
  - 1.8.3
  - 1.9
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  # more recent version of ruby is required for sinatra
  - rvm install 2.2.4
  # gem install must be run with sudo on OSX
  - sudo gem install asciidoctor sinatra --no-ri --no-rdoc | gem install asciidoctor sinatra --no-ri --no-rdoc
  - sudo pip install docutils flask
script:
  - go test -race -v ./...