sudo: false
language: go
env:
    - GIMME_ARCH=amd64
go:
  - 1.7.6
  - 1.8.3
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script: 
  - go test -race -v ./...